/**
 * Seed script for pet products - Chinese market catalog
 * Run with: npx tsx scripts/seed-products.ts
 */

import { config } from 'dotenv';
config({ path: '.env.local' });

import { createCollection, dropCollection, insertProducts, type Product } from '../src/services/zilliz';

// Comprehensive Chinese pet products catalog (72 products across 12 categories)
// Based on products sold in China via JD.com, Tmall, and major pet platforms (2024-2025)
const SAMPLE_PRODUCTS: Product[] = [

  // =============================================================================
  // 1. 伤口护理 WOUND CARE (6 products)
  // =============================================================================
  {
    id: 'cn-wc-001',
    name: '普安特宠物伤口消炎喷雾 100ml',
    brand: '普安特 PUAINTA',
    category: 'wound-care',
    description: '宠物专用广谱抗菌喷雾，含次氯酸成分，可有效杀灭伤口处细菌和真菌，促进愈合。无刺激、无酒精配方，可直接喷于猫狗伤口、术后切口、擦伤部位，使用安全方便。',
    conditions: ['伤口感染', '皮肤外伤', '术后护理', '擦伤', '抓伤'],
    pet_types: ['dog', 'cat'],
    price: 38,
    image_url: '',
    product_url: 'https://ispuainta.com',
  },
  {
    id: 'cn-wc-002',
    name: '维克氯己定抗菌伤口喷雾 150ml',
    brand: '维克 Virbac',
    category: 'wound-care',
    description: '法国维克出品的专业宠物伤口清洁喷雾，主要成分为氯己定（洗必泰），能有效清洁并消毒伤口，防止继发感染，适用于猫狗各类体表外伤的日常护理。',
    conditions: ['伤口清洁', '擦伤', '皮肤溃疡', '术后护理'],
    pet_types: ['dog', 'cat'],
    price: 68,
    image_url: '',
    product_url: 'https://www.virbac.cn',
  },
  {
    id: 'cn-wc-003',
    name: '小宠宠物软性防舔圈（伊丽莎白圈）多尺寸',
    brand: '小宠 XiaoChong',
    category: 'wound-care',
    description: '采用柔软弹力布料制作的防舔圈，相较于传统硬质塑料圈更舒适，宠物可正常进食饮水和睡觉。有效防止猫狗舔舐伤口或术后切口，加速愈合，尺寸覆盖XS至XL。',
    conditions: ['术后防舔', '伤口保护', '皮肤病护理', '绝育术后'],
    pet_types: ['dog', 'cat'],
    price: 35,
    image_url: '',
    product_url: 'https://www.xiaochongpet.com',
  },
  {
    id: 'cn-wc-004',
    name: '佩帝宠物术后恢复服（公母款）',
    brand: '佩帝 Paddy',
    category: 'wound-care',
    description: '全棉舒适面料制成的宠物术后保护服，可代替传统伊丽莎白圈，全方位包裹腹部伤口，防止舔舐与抓挠。适用于绝育、剖腹产等腹部手术后的恢复期，分公猫/母猫/犬款。',
    conditions: ['术后恢复', '伤口保护', '绝育术后', '腹部手术'],
    pet_types: ['dog', 'cat'],
    price: 59,
    image_url: '',
    product_url: 'https://www.pddypet.com',
  },
  {
    id: 'cn-wc-005',
    name: '诺恩宠物皮肤修复喷雾 120ml',
    brand: '诺恩 Noen',
    category: 'wound-care',
    description: '采用次氯酸水技术的宠物皮肤修复喷雾，有效成分可快速消杀95%以上细菌，同时促进皮肤细胞再生，适用于宠物外伤、湿疹、热点炎症及术后伤口的日常护理。',
    conditions: ['皮肤外伤', '湿疹', '热点炎症', '细菌感染'],
    pet_types: ['dog', 'cat'],
    price: 45,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-wc-006',
    name: '艾贝特宠物硬质伊丽莎白圈透明款',
    brand: '艾贝特 Albert',
    category: 'wound-care',
    description: '高透明度PC材料制成的宠物防舔圈，轻巧耐用，全透明设计减少宠物压迫感，颈部衬垫柔软舒适。适用于各类手术后护理、伤口保护和皮肤病辅助治疗。',
    conditions: ['术后防舔', '伤口保护', '皮肤病护理'],
    pet_types: ['dog', 'cat'],
    price: 28,
    image_url: '',
    product_url: '',
  },

  // =============================================================================
  // 2. 消化健康 DIGESTIVE HEALTH (6 products)
  // =============================================================================
  {
    id: 'cn-dh-001',
    name: 'MAG犬用布拉迪益生菌粉 30袋/盒',
    brand: 'MAG美格',
    category: 'digestive-health',
    description: '以布拉迪酵母菌为核心成分的宠物专用益生菌，专为狗狗胃肠菌群特点研发，能有效改善软便、腹泻、呕吐等肠胃不适症状，增强肠道屏障功能，适合幼犬及成年犬日常调理。',
    conditions: ['腹泻', '软便', '呕吐', '肠胃不适', '消化不良'],
    pet_types: ['dog'],
    price: 128,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-dh-002',
    name: '卫仕宠物益生菌猫咪肠胃宝 200g',
    brand: '卫仕 NOURSE',
    category: 'digestive-health',
    description: '猫犬通用型益生菌产品，含多菌株复合益生菌及益生元，有效调节肠道菌群平衡，改善幼猫幼犬常见腹泻、软便问题，粉末状易于拌入食物，适口性好。',
    conditions: ['腹泻', '软便', '肠道菌群失调', '消化不良', '肠胃调理'],
    pet_types: ['dog', 'cat'],
    price: 89,
    image_url: '',
    product_url: 'https://www.nourse.com.cn',
  },
  {
    id: 'cn-dh-003',
    name: '麦富迪宠物即溶益生菌军团 24袋',
    brand: '麦富迪 Myfoodie',
    category: 'digestive-health',
    description: '采用冻干技术保活的复合型宠物益生菌，含益生菌、益生元及天然植萃精华，搭配冻干肉粉提升适口性，可有效改善宠物消化系统功能，维持肠道微生态平衡。',
    conditions: ['消化不良', '腹泻', '肠道健康维护', '挑食'],
    pet_types: ['dog', 'cat'],
    price: 79,
    image_url: '',
    product_url: 'https://www.myfoodiepet.com',
  },
  {
    id: 'cn-dh-004',
    name: '卫仕宠物南瓜纤维粉 100g',
    brand: '卫仕 NOURSE',
    category: 'digestive-health',
    description: '以天然南瓜为原料制成的宠物膳食纤维粉，可有效促进肠道蠕动，帮助调节宠物便秘与轻度腹泻，还具有一定化毛作用，适合猫咪日常肠道护理，可轻松拌入主食。',
    conditions: ['便秘', '轻度腹泻', '化毛', '肠道调理', '肠道纤维不足'],
    pet_types: ['dog', 'cat'],
    price: 45,
    image_url: '',
    product_url: 'https://www.nourse.com.cn',
  },
  {
    id: 'cn-dh-005',
    name: '普安特宠物止泻整肠液 20ml×6支',
    brand: '普安特 PUAINTA',
    category: 'digestive-health',
    description: '兽医专研的宠物专用止泻整肠液，含蒙脱石散成分，能迅速吸附肠道内毒素与细菌，稳固肠道黏膜，快速缓解猫狗急性腹泻，使用方便，可直接口服或拌食。',
    conditions: ['急性腹泻', '软便', '肠道感染', '应激性腹泻'],
    pet_types: ['dog', 'cat'],
    price: 55,
    image_url: '',
    product_url: 'https://ispuainta.com',
  },
  {
    id: 'cn-dh-006',
    name: '谷登宠物消化酶益生菌合剂 60g',
    brand: '谷登 GOLDEN',
    category: 'digestive-health',
    description: '将多种消化酶（淀粉酶、蛋白酶、脂肪酶）与复合益生菌结合的全效肠道保健产品，帮助宠物充分分解食物、改善营养吸收率，缓解食物不耐受引起的胀气和消化不良。',
    conditions: ['消化不良', '胀气', '营养吸收差', '食物不耐受', '便秘'],
    pet_types: ['dog', 'cat'],
    price: 65,
    image_url: '',
    product_url: '',
  },

  // =============================================================================
  // 3. 耳道护理 EAR CARE (6 products)
  // =============================================================================
  {
    id: 'cn-ec-001',
    name: '维克耳可舒宠物洗耳液 100ml',
    brand: '维克 Virbac',
    category: 'ear-care',
    description: '法国维克出品的宠物专业洗耳液，含温和表面活性剂和水杨酸成分，可有效溶解耳垢、消除异味，适用于细菌、真菌及马拉色菌引起的外耳炎症护理，猫狗通用。',
    conditions: ['外耳炎', '耳垢堆积', '耳道异味', '耳道真菌感染', '马拉色菌'],
    pet_types: ['dog', 'cat'],
    price: 95,
    image_url: '',
    product_url: 'https://www.virbac.cn',
  },
  {
    id: 'cn-ec-002',
    name: '金盾尔康宠物耳螨滴耳液 20ml',
    brand: '金盾 JINDUN',
    category: 'ear-care',
    description: '国产兽药级滴耳液，含盐酸小檗碱与抗真菌成分，专门针对耳螨、细菌及真菌引起的耳道炎症，可有效止痒、消炎，清除耳道内寄生虫，适用于猫狗耳螨感染。',
    conditions: ['耳螨', '外耳炎', '耳道瘙痒', '细菌性耳炎', '甩头抓耳'],
    pet_types: ['dog', 'cat'],
    price: 42,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-ec-003',
    name: '小宠宠物洗耳液猫咪狗狗耳道清洁 125ml',
    brand: '小宠 XiaoChong',
    category: 'ear-care',
    description: '温和无刺激的宠物日常洗耳液，以天然植萃成分为基础，有效软化并清除耳道内过多耳垢，防止细菌滋生，适合长耳朵犬种（如比格、可卡、腊肠犬）的日常耳道护理。',
    conditions: ['耳垢堆积', '耳道日常清洁', '预防耳道感染', '耳道异味'],
    pet_types: ['dog', 'cat'],
    price: 39,
    image_url: '',
    product_url: 'https://www.xiaochongpet.com',
  },
  {
    id: 'cn-ec-004',
    name: '众诚方源耳康宠物耳道消炎液 15ml',
    brand: '众诚方源',
    category: 'ear-care',
    description: '经临床验证的国产耳道消炎液，含盐酸达克罗宁与盐酸小檗碱，对细菌、真菌及耳螨引起的各种耳道炎症均有明显疗效，可消炎止痒，是宠物主的家庭常备耳道用药。',
    conditions: ['耳道感染', '耳螨', '外耳炎', '耳道瘙痒', '细菌真菌混合感染'],
    pet_types: ['dog', 'cat'],
    price: 35,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-ec-005',
    name: '雷米高益尔净复方制霉菌素软膏 15g',
    brand: '雷米高 Ramical',
    category: 'ear-care',
    description: '中澳合资品牌雷米高出品的复方耳道软膏，含制霉菌素与抗炎成分，专门用于治疗真菌性外耳炎及耳螨感染，膏体质地易涂抹，药物持效时间长，适合慢性耳炎管理。',
    conditions: ['真菌性耳炎', '耳螨', '慢性外耳炎', '耳道皮肤炎症'],
    pet_types: ['dog', 'cat'],
    price: 58,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-ec-006',
    name: '维百宠宠物耳道清洁湿巾 40片/包',
    brand: '维百宠 VPets',
    category: 'ear-care',
    description: '宠物专用一次性耳道清洁湿巾，含温和抗菌成分，可方便快捷地清除耳廓及外耳道浅表污垢，适合日常外出后耳道清洁，使用方便，无酒精无刺激。',
    conditions: ['耳道日常清洁', '外出后护理', '轻度耳垢'],
    pet_types: ['dog', 'cat'],
    price: 28,
    image_url: '',
    product_url: '',
  },

  // =============================================================================
  // 4. 眼部护理 EYE CARE (6 products)
  // =============================================================================
  {
    id: 'cn-eye-001',
    name: '普安特宠物硫酸新霉素滴眼液 8ml',
    brand: '普安特 PUAINTA',
    category: 'eye-care',
    description: '宠物专用广谱抗菌滴眼液，主要成分为硫酸新霉素，可有效治疗结膜炎、角膜炎等细菌性眼部感染，同时帮助清洁眼睛分泌物，猫犬通用，月销量超万件。',
    conditions: ['结膜炎', '眼部感染', '眼屎增多', '眼睛发炎', '流泪'],
    pet_types: ['dog', 'cat'],
    price: 39,
    image_url: '',
    product_url: 'https://ispuainta.com',
  },
  {
    id: 'cn-eye-002',
    name: '唯特医生宠物泪痕去除滴眼液 10ml',
    brand: '唯特医生 VetDoctor',
    category: 'eye-care',
    description: '专为宠物泪痕问题设计的滴眼液，温和植物配方可有效清洁泪痕区域，防止泪痕色素沉积，长期使用可显著改善白色及浅色宠物眼周泪痕问题，适合比熊、博美等犬种。',
    conditions: ['泪痕', '眼周染色', '眼分泌物', '眼睛清洁'],
    pet_types: ['dog', 'cat'],
    price: 48,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-eye-003',
    name: '杰维士宠物眼药水消炎滴眼液 8ml',
    brand: '杰维士 Gervis',
    category: 'eye-care',
    description: '宠物用消炎滴眼液，含抗菌及消炎成分，可迅速缓解结膜炎、角膜炎等引起的红肿充血、流泪及眼屎增多症状，适合猫咪和狗狗急性眼部感染的家庭初步处理。',
    conditions: ['眼睛发炎', '结膜炎', '角膜炎', '眼睛充血', '眼屎过多'],
    pet_types: ['dog', 'cat'],
    price: 35,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-eye-004',
    name: 'alican宠物泪痕液内服改善液 60ml',
    brand: 'alican',
    category: 'eye-care',
    description: '从源头调理泪痕问题的口服液，采用天然草本与动物提取物复配配方，优化肝胆代谢，促进泪液中卟啉物质排出，从根本减少色素沉积，适合泪痕严重或顽固的宠物长期使用。',
    conditions: ['泪痕', '卟啉沉积', '泪液过多', '眼周染色'],
    pet_types: ['dog', 'cat'],
    price: 85,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-eye-005',
    name: '真宠良品MAJI宠物眼部清洁湿巾 100片',
    brand: '真宠良品 MAJI',
    category: 'eye-care',
    description: '宠物眼部专用一次性清洁湿巾，以温和无刺激配方制成，可有效清除眼睛周围的泪痕、眼屎及污垢，长期使用有助于减少泪痕色素沉积，适合日常眼部清洁护理。',
    conditions: ['日常眼部清洁', '泪痕预防', '眼屎清除', '眼周护理'],
    pet_types: ['dog', 'cat'],
    price: 32,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-eye-006',
    name: '维克宠物眼部清洗液 100ml',
    brand: '维克 Virbac',
    category: 'eye-care',
    description: '法国维克专业宠物眼部清洗液，等渗生理盐水配方，可温和冲洗眼部异物、分泌物及轻度刺激物，适合宠物眼部日常清洁及过敏性眼炎的辅助护理，猫狗通用。',
    conditions: ['眼部异物', '过敏性眼炎', '眼部清洁', '眼分泌物'],
    pet_types: ['dog', 'cat'],
    price: 55,
    image_url: '',
    product_url: 'https://www.virbac.cn',
  },

  // =============================================================================
  // 5. 皮肤护理 SKIN CARE (6 products)
  // =============================================================================
  {
    id: 'cn-sc-001',
    name: '维克宠物氯己定抗菌药浴香波 250ml',
    brand: '维克 Virbac',
    category: 'skin-care',
    description: '法国维克出品的宠物专业药浴洗毛水，含3%氯己定与2%酮康唑，可有效治疗犬猫细菌性及真菌性皮肤病，适用于脓皮症、皮肤真菌感染等，宠物医院推荐使用。',
    conditions: ['脓皮症', '真菌感染', '皮肤炎症', '皮癣', '毛囊炎'],
    pet_types: ['dog', 'cat'],
    price: 118,
    image_url: '',
    product_url: 'https://www.virbac.cn',
  },
  {
    id: 'cn-sc-002',
    name: '爱皮舒宠物止痒舒缓喷雾 200ml',
    brand: '爱皮舒',
    category: 'skin-care',
    description: '针对宠物皮肤瘙痒设计的快效止痒喷雾，含燕麦提取物与芦荟，能迅速缓解因过敏、热点炎症、蚊虫叮咬引起的皮肤瘙痒，修复皮肤屏障，无激素配方，适合敏感肤质宠物。',
    conditions: ['皮肤瘙痒', '过敏性皮炎', '热点炎症', '蚊虫叮咬', '皮肤干燥'],
    pet_types: ['dog', 'cat'],
    price: 58,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-sc-003',
    name: '卫仕宠物深海鱼油软胶囊 100粒',
    brand: '卫仕 NOURSE',
    category: 'skin-care',
    description: '提取自深海鱼类的高纯度Omega-3鱼油软胶囊，含丰富EPA和DHA，长期服用可改善宠物皮肤干燥、毛发暗淡、掉毛等问题，同时有助于缓解关节炎症，猫狗通用。',
    conditions: ['皮肤干燥', '毛发暗淡', '过度掉毛', '皮肤过敏', '关节炎症'],
    pet_types: ['dog', 'cat'],
    price: 69,
    image_url: '',
    product_url: 'https://www.nourse.com.cn',
  },
  {
    id: 'cn-sc-004',
    name: '麦富迪宠物燕麦舒缓洗毛水 500ml',
    brand: '麦富迪 Myfoodie',
    category: 'skin-care',
    description: '以胶体燕麦为核心成分的宠物敏感皮肤专用洗毛水，温和低刺激配方不破坏皮肤天然油脂，可有效缓解皮肤瘙痒干燥，保湿锁水，适合皮肤敏感或患有过敏性皮炎的宠物。',
    conditions: ['敏感皮肤', '皮肤瘙痒', '干燥脱皮', '过敏性皮炎'],
    pet_types: ['dog', 'cat'],
    price: 55,
    image_url: '',
    product_url: 'https://www.myfoodiepet.com',
  },
  {
    id: 'cn-sc-005',
    name: '倔强熊宠物神经酰胺皮肤修复乳 100ml',
    brand: '倔强熊',
    category: 'skin-care',
    description: '含神经酰胺与积雪草提取物的宠物皮肤修复护理乳，专门用于修复受损皮肤屏障，改善慢性皮肤炎症、干燥脱皮问题，沐浴后使用效果更佳，质地轻薄不油腻。',
    conditions: ['皮肤屏障受损', '慢性皮炎', '皮肤干燥', '过敏性皮肤', '脱皮'],
    pet_types: ['dog', 'cat'],
    price: 78,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-sc-006',
    name: '派乐特宠物酮康唑抗真菌香波 200ml',
    brand: '派乐特 Pailet',
    category: 'skin-care',
    description: '含1%酮康唑成分的宠物抗真菌专用药浴香波，可有效治疗皮肤癣菌病、马拉色菌皮炎等真菌性皮肤疾病，同时改善相关皮肤瘙痒和异味，适合配合兽医治疗使用。',
    conditions: ['皮肤真菌感染', '皮癣', '马拉色菌皮炎', '皮肤瘙痒', '皮肤异味'],
    pet_types: ['dog', 'cat'],
    price: 72,
    image_url: '',
    product_url: '',
  },

  // =============================================================================
  // 6. 过敏护理 ALLERGY RELIEF (6 products)
  // =============================================================================
  {
    id: 'cn-ar-001',
    name: '礼舒替尼宠物过敏止痒片（处方药需遵医嘱）',
    brand: '格格巫生物 GeGeWu Bio',
    category: 'allergy-relief',
    description: '中国首款一类宠物创新药，以JAK激酶为靶点的犬用止痒药物，专门用于控制犬过敏性皮炎引起的瘙痒，疗效确切、起效迅速，处方药需在兽医指导下使用。',
    conditions: ['过敏性皮炎', '顽固性瘙痒', '特应性皮炎', '过敏性瘙痒'],
    pet_types: ['dog'],
    price: 280,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-ar-002',
    name: '卫仕宠物抗过敏益生菌胶囊 30粒',
    brand: '卫仕 NOURSE',
    category: 'allergy-relief',
    description: '含特定免疫调节菌株的宠物抗过敏益生菌，通过调节肠道免疫轴降低机体过敏反应，长期服用可显著减轻食物性和环境性过敏症状，适合有慢性过敏体质的猫狗使用。',
    conditions: ['食物过敏', '环境过敏', '花粉过敏', '皮肤过敏', '过敏体质调理'],
    pet_types: ['dog', 'cat'],
    price: 98,
    image_url: '',
    product_url: 'https://www.nourse.com.cn',
  },
  {
    id: 'cn-ar-003',
    name: 'MAG宠物免疫过敏营养补充剂 60片',
    brand: 'MAG美格',
    category: 'allergy-relief',
    description: '专为过敏体质宠物设计的营养素补充片，含螺旋藻、β-葡聚糖及特定维生素组合，通过全面提升免疫调节能力来降低过敏反应频率，适合季节性过敏或食物不耐受的宠物。',
    conditions: ['季节性过敏', '食物不耐受', '免疫调节', '慢性过敏', '皮肤过敏'],
    pet_types: ['dog', 'cat'],
    price: 118,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-ar-004',
    name: '普安特宠物苯海拉明止痒片（遵医嘱使用）',
    brand: '普安特 PUAINTA',
    category: 'allergy-relief',
    description: '宠物专用抗组胺药物，含苯海拉明成分，可快速缓解由过敏反应引起的皮肤瘙痒、荨麻疹及蚊虫叮咬后的局部红肿，用药剂量需根据宠物体重在兽医指导下确定。',
    conditions: ['急性过敏反应', '荨麻疹', '皮肤瘙痒', '蚊虫叮咬', '过敏性皮疹'],
    pet_types: ['dog', 'cat'],
    price: 45,
    image_url: '',
    product_url: 'https://ispuainta.com',
  },
  {
    id: 'cn-ar-005',
    name: '红狗宠物肠道过敏营养粉 100g',
    brand: '红狗 RedDog',
    category: 'allergy-relief',
    description: '针对肠道食物过敏的宠物营养补充粉，含水解蛋白肽、益生菌及多种抗氧化成分，可改善食物过敏引起的皮肤问题、肠胃不适及慢性软便，适合过敏体质宠物长期调理使用。',
    conditions: ['食物过敏', '肠道过敏', '过敏性皮炎', '慢性软便', '慢性肠炎'],
    pet_types: ['dog', 'cat'],
    price: 88,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-ar-006',
    name: 'IN-PLUS麦德氏宠物过敏肤质专用鱼油 300ml',
    brand: 'IN-PLUS 麦德氏',
    category: 'allergy-relief',
    description: '针对过敏性皮肤病专门研发的高浓度鱼油，富含抗炎Omega-3脂肪酸，可从根本减轻过敏性皮炎炎症反应，改善皮肤屏障功能，配合抗过敏治疗效果显著。',
    conditions: ['过敏性皮炎', '皮肤炎症', '慢性过敏', '皮肤屏障受损'],
    pet_types: ['dog', 'cat'],
    price: 135,
    image_url: '',
    product_url: '',
  },

  // =============================================================================
  // 7. 焦虑缓解 ANXIETY RELIEF (6 products)
  // =============================================================================
  {
    id: 'cn-anx-001',
    name: '费利威经典猫咪费洛蒙扩香套装 30天量',
    brand: '费利威 FELIWAY',
    category: 'anxiety-relief',
    description: '法国进口合成猫面部费洛蒙扩香器套装，通过释放猫咪熟悉的安抚信息素有效缓解猫咪应激反应，减少乱尿、过度抓挠、躲避等焦虑行为，覆盖约70平方米空间。',
    conditions: ['猫咪焦虑', '应激反应', '乱尿', '过度抓挠', '搬家适应', '多猫冲突'],
    pet_types: ['cat'],
    price: 220,
    image_url: '',
    product_url: 'https://www.feliway.com',
  },
  {
    id: 'cn-anx-002',
    name: '费利威经典猫咪费洛蒙应激喷雾 20ml',
    brand: '费利威 FELIWAY',
    category: 'anxiety-relief',
    description: '便携式合成猫面部费洛蒙喷雾，特别适合外出就医、乘车或宠物局部区域的应激缓解，直接喷于猫笼或毯子上，15分钟后放入猫咪，有效降低应激引起的攻击行为。',
    conditions: ['就医应激', '出行焦虑', '短期应激', '猫咪攻击性', '猫咪焦虑'],
    pet_types: ['cat'],
    price: 95,
    image_url: '',
    product_url: 'https://www.feliway.com',
  },
  {
    id: 'cn-anx-003',
    name: '宠物平衡安抚马甲犬用（XS-XL）',
    brand: '倔强熊',
    category: 'anxiety-relief',
    description: '仿照"深压疗法"原理设计的宠物安抚马甲，通过持续轻柔地施压于犬只躯干，自然地缓解因雷雨、鞭炮、分离等引起的焦虑情绪，弹力透气面料，穿戴舒适。',
    conditions: ['雷雨恐惧', '鞭炮焦虑', '分离焦虑', '出行紧张', '烟花恐惧'],
    pet_types: ['dog'],
    price: 168,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-anx-004',
    name: '卫仕宠物安神镇定零食（猫咪款）40g',
    brand: '卫仕 NOURSE',
    category: 'anxiety-relief',
    description: '含L-茶氨酸、洋甘菊提取物与缬草根的猫咪专用安抚功能零食，可有效缓解猫咪因陌生环境、就医、运输引起的焦虑紧张情绪，无镇静成分，日常可辅助使用。',
    conditions: ['猫咪焦虑', '就医应激', '出行紧张', '环境适应', '陌生访客'],
    pet_types: ['cat'],
    price: 75,
    image_url: '',
    product_url: 'https://www.nourse.com.cn',
  },
  {
    id: 'cn-anx-005',
    name: '麦德氏IN-PLUS宠物情绪调节软糖（犬用）30粒',
    brand: 'IN-PLUS 麦德氏',
    category: 'anxiety-relief',
    description: '美国ALC研发团队出品的犬用镇定功能软糖，含L-色氨酸、迷迭香精华和维生素B群，通过天然途径调节神经系统，缓解犬只慢性焦虑和过度兴奋，适合日常补充。',
    conditions: ['分离焦虑', '过度兴奋', '慢性焦虑', '行为问题', '噪音恐惧'],
    pet_types: ['dog'],
    price: 128,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-anx-006',
    name: '普安特宠物植物镇定滴剂 30ml（猫狗通用）',
    brand: '普安特 PUAINTA',
    category: 'anxiety-relief',
    description: '以纯植物提取物配制的宠物情绪舒缓口服滴剂，含西番莲、缬草根及洋甘菊精华，可帮助猫狗在应激事件前后快速进入放松状态，无依赖性，可短期或长期使用。',
    conditions: ['应激反应', '焦虑紧张', '猫咪打架', '出行应激', '节假日噪音'],
    pet_types: ['dog', 'cat'],
    price: 68,
    image_url: '',
    product_url: 'https://ispuainta.com',
  },

  // =============================================================================
  // 8. 急救备用 FIRST AID (6 products)
  // =============================================================================
  {
    id: 'cn-fa-001',
    name: '普安特宠物家庭急救箱套装（20件组）',
    brand: '普安特 PUAINTA',
    category: 'first-aid',
    description: '家庭宠物急救必备套装，内含消毒棉球、无菌纱布、自粘绷带、医用剪刀、镊子、体温计及急救操作指南，适合猫狗常见外伤、出血等紧急情况的初步处理。',
    conditions: ['外伤急救', '出血处理', '伤口包扎', '外出旅行备用', '紧急处理'],
    pet_types: ['dog', 'cat'],
    price: 88,
    image_url: '',
    product_url: 'https://ispuainta.com',
  },
  {
    id: 'cn-fa-002',
    name: '蓝帆医疗宠物专用止血粉 30g',
    brand: '蓝帆医疗 Bluesail',
    category: 'first-aid',
    description: '专业快效止血粉，主要成分为硫酸铁，接触出血伤口后迅速形成凝块，数秒内止住出血，特别适用于宠物剪指甲剪过时的止血及体表小伤口处理，是宠物主的必备急救用品。',
    conditions: ['指甲出血', '轻微割伤', '体表出血', '止血急救'],
    pet_types: ['dog', 'cat'],
    price: 35,
    image_url: '',
    product_url: 'https://www.bluesail.com.cn',
  },
  {
    id: 'cn-fa-003',
    name: '3M Vetrap宠物自粘弹力绷带 5cm×4.5m',
    brand: '3M',
    category: 'first-aid',
    description: '医用级自粘弹性绷带，只粘绷带自身不粘毛发和皮肤，轻便透气，可用于宠物伤口包扎、腿部固定及保护纱布敷料，撕拉方便，多色可选，猫狗通用。',
    conditions: ['伤口包扎', '骨折固定', '腿部保护', '纱布固定'],
    pet_types: ['dog', 'cat'],
    price: 22,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-fa-004',
    name: '艾贝特宠物电子体温计（快速测量型）',
    brand: '艾贝特 Albert',
    category: 'first-aid',
    description: '宠物专用数字电子体温计，采用灵活软性探头设计，减少宠物不适感，10秒快速测温，发热报警功能，存储上次测量结果，是家庭宠物健康监测的必备工具。',
    conditions: ['发热监测', '疾病早期识别', '术后体温监控', '日常健康检查'],
    pet_types: ['dog', 'cat'],
    price: 48,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-fa-005',
    name: '小宠宠物活性炭急救片（宠物催吐/排毒辅助）',
    brand: '小宠 XiaoChong',
    category: 'first-aid',
    description: '宠物专用活性炭片，可在宠物误食轻度有毒食物后（在兽医指导下）辅助吸附胃肠道内的毒素，减少毒物吸收，但严重中毒情况须立即就医，不可替代兽医治疗。',
    conditions: ['轻度中毒', '误食有害食物', '毒素吸附', '肠道排毒'],
    pet_types: ['dog', 'cat'],
    price: 42,
    image_url: '',
    product_url: 'https://www.xiaochongpet.com',
  },
  {
    id: 'cn-fa-006',
    name: '维百宠宠物医用纱布敷料 10cm×10cm（10片装）',
    brand: '维百宠 VPets',
    category: 'first-aid',
    description: '宠物专用无菌医用纱布，高吸水性面料，可有效吸收伤口渗出液，配合消毒喷雾和自粘绷带使用，适合宠物中等体积伤口的覆盖保护与换药处理。',
    conditions: ['伤口覆盖', '手术后换药', '渗出液吸收', '伤口保护'],
    pet_types: ['dog', 'cat'],
    price: 18,
    image_url: '',
    product_url: '',
  },

  // =============================================================================
  // 9. 口腔护理 DENTAL CARE (6 products)
  // =============================================================================
  {
    id: 'cn-dc-001',
    name: '小壳CATURE宠物益生菌洁齿水 500ml',
    brand: '小壳 CATURE',
    category: 'dental-care',
    description: '由小壳实验室研发的宠物益生菌洁齿水，每天加入饮水中即可持续清洁口腔，抑制牙菌斑与牙结石形成，有效改善口臭，天然植物提取成分，无味无色，全国20000+宠物门店同步销售。',
    conditions: ['口臭', '牙菌斑', '牙结石', '口腔清洁', '牙龈炎预防'],
    pet_types: ['dog', 'cat'],
    price: 68,
    image_url: '',
    product_url: 'https://www.cature.cn',
  },
  {
    id: 'cn-dc-002',
    name: '多美洁Tropiclean天然洁齿凝露（成犬用）59ml',
    brand: '多美洁 Tropiclean',
    category: 'dental-care',
    description: '美国进口天然洁齿凝露，无需刷牙，直接涂抹于牙龈，含绿茶精华与肉桂提取物，可有效去除牙垢、改善口气，获得美国兽医口腔健康委员会认证，口感好适口性强。',
    conditions: ['口臭', '牙菌斑', '牙结石', '不愿刷牙的宠物'],
    pet_types: ['dog'],
    price: 78,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-dc-003',
    name: '维克C.E.T.酶促宠物牙膏 70g（鸡肉味）',
    brand: '维克 Virbac',
    category: 'dental-care',
    description: '法国维克专业酶促型宠物牙膏，含双链抗菌酶系统，通过酶化学反应抑制细菌在牙面附着，有效预防牙菌斑和牙结石，鸡肉口味适口性好，无需漂洗，猫狗适用。',
    conditions: ['牙菌斑', '牙结石', '口臭', '牙龈炎', '口腔健康维护'],
    pet_types: ['dog', 'cat'],
    price: 65,
    image_url: '',
    product_url: 'https://www.virbac.cn',
  },
  {
    id: 'cn-dc-004',
    name: '法国皇家宠物洁牙棒（中型犬用）7支装',
    brand: '法国皇家 Royal Canin',
    category: 'dental-care',
    description: '法国皇家出品的宠物洁牙零食，独特的立体咀嚼形状可全方位清洁牙齿，通过物理磨损减少牙结石积累，含益生元和特殊矿物质，维护口腔环境健康，每天一根即可。',
    conditions: ['牙结石', '口臭', '牙龈健康', '口腔维护'],
    pet_types: ['dog'],
    price: 85,
    image_url: '',
    product_url: 'https://www.royalcanin.cn',
  },
  {
    id: 'cn-dc-005',
    name: '素力高Solid Gold冻干洁齿棒（猫用）50g',
    brand: '素力高 Solid Gold',
    category: 'dental-care',
    description: '健合集团出品的猫咪冻干洁齿棒，采用高蛋白冻干肉块与洁齿纤维结合技术，既满足猫咪食肉需求又达到物理洁齿效果，有助于减少牙结石，适合不喜欢刷牙的猫咪。',
    conditions: ['牙结石', '牙菌斑', '口腔清洁', '猫咪口腔健康'],
    pet_types: ['cat'],
    price: 72,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-dc-006',
    name: '氧亲新OXYFRESH宠物口腔护理水 236ml',
    brand: '氧亲新 OXYFRESH',
    category: 'dental-care',
    description: '美国进口宠物口腔护理水，美国兽医协会推荐，在全美专业口腔护理品牌中销量第一。每天加入饮水中即可中和口腔中的细菌代谢产物，从根源消除口臭，无味无色无酒精。',
    conditions: ['口臭', '细菌性口腔疾病', '口腔卫生维护', '牙龈炎'],
    pet_types: ['dog', 'cat'],
    price: 95,
    image_url: '',
    product_url: '',
  },

  // =============================================================================
  // 10. 关节健康 JOINT HEALTH (6 products)
  // =============================================================================
  {
    id: 'cn-jh-001',
    name: 'MAG宠物软骨素关节保健品 60片',
    brand: 'MAG美格',
    category: 'joint-health',
    description: '2024年第26届亚宠展年度实力医疗保健大奖得主，氨基葡萄糖和硫酸软骨素（鲨鱼软骨素）总含量超过50%，是目前国内软骨素含量最高的宠物关节产品之一，宠物医院首选。',
    conditions: ['关节炎', '髋关节发育不良', '关节疼痛', '行动迟缓', '老年关节退化'],
    pet_types: ['dog', 'cat'],
    price: 198,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-jh-002',
    name: '麦德氏IN-PLUS鲨鱼软骨素关节灵 60片',
    brand: 'IN-PLUS 麦德氏',
    category: 'joint-health',
    description: '美国ALC宠物食品集团专业兽医团队研发，含BCM-95鲨鱼软骨素与高纯度氨基葡萄糖，专为宠物关节软骨修复和润滑设计，适合有关节问题或老年宠物每日补充。',
    conditions: ['关节炎', '软骨损伤', '关节疼痛', '老年宠物关节退化', '髋关节问题'],
    pet_types: ['dog', 'cat'],
    price: 168,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-jh-003',
    name: '卫仕宠物氨糖软骨素关节片 100片',
    brand: '卫仕 NOURSE',
    category: 'joint-health',
    description: '卫仕出品的宠物关节保健产品，含硫酸氨基葡萄糖、硫酸软骨素及维生素C，可促进关节软骨液分泌，减少关节摩擦与炎症，适合大型犬及老年猫狗的关节日常保健。',
    conditions: ['关节炎', '关节疼痛', '软骨磨损', '老年宠物', '大型犬关节保健'],
    pet_types: ['dog', 'cat'],
    price: 128,
    image_url: '',
    product_url: 'https://www.nourse.com.cn',
  },
  {
    id: 'cn-jh-004',
    name: 'VONEOS宠物医护版鲨鱼软骨素 60粒',
    brand: 'VONEOS',
    category: 'joint-health',
    description: '2024年亚宠展新品，以深海鲨鱼软骨素为核心成分，协调高含量葡萄糖胺，能有效促进受损软骨再生，修复关节液，适用于各种原因引起的宠物关节问题及术后关节恢复。',
    conditions: ['软骨损伤', '关节炎', '术后关节恢复', '关节疼痛', '行走困难'],
    pet_types: ['dog', 'cat'],
    price: 188,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-jh-005',
    name: '法国皇家老年犬关节护理主粮配方（处方粮J/D）',
    brand: '法国皇家 Royal Canin',
    category: 'joint-health',
    description: '法国皇家专为关节疾病犬设计的处方粮，含高浓度Omega-3脂肪酸EPA/DHA、葡萄糖胺和硫酸软骨素，可显著改善行走能力，需在兽医建议下使用，适合长期饲喂。',
    conditions: ['骨关节炎', '关节退行性病变', '长期关节管理', '行动能力下降'],
    pet_types: ['dog'],
    price: 320,
    image_url: '',
    product_url: 'https://www.royalcanin.cn',
  },
  {
    id: 'cn-jh-006',
    name: '谷登GOLDEN宠物关节软骨营养液 200ml',
    brand: '谷登 GOLDEN',
    category: 'joint-health',
    description: '液态关节保健营养液，含水解Ⅱ型胶原蛋白、透明质酸及二甲基砜（MSM），协同促进关节软骨健康和关节腔润滑，液体形态吸收率高，特别适合不愿吃片剂的挑剔宠物。',
    conditions: ['关节疼痛', '软骨保护', '老年宠物关节保健', '关节液不足'],
    pet_types: ['dog', 'cat'],
    price: 138,
    image_url: '',
    product_url: '',
  },

  // =============================================================================
  // 11. 宠物驱虫防螨 PEST / PARASITE PREVENTION (6 products)
  // =============================================================================
  {
    id: 'cn-pp-001',
    name: '大宠爱赛拉菌素犬用体内外驱虫滴剂（L号）',
    brand: '大宠爱 Revolution（硕腾 Zoetis）',
    category: 'pest-prevention',
    description: '硕腾出品的全球知名宠物体内外全面驱虫产品，主要成分赛拉菌素，一次滴剂同步驱除跳蚤、蜱虫、耳螨、线虫、心丝虫等多种寄生虫，预防期长达30天，是宠物医院推荐首选。',
    conditions: ['跳蚤', '蜱虫', '耳螨', '线虫', '心丝虫预防', '体内外驱虫'],
    pet_types: ['dog', 'cat'],
    price: 128,
    image_url: '',
    product_url: 'https://www.zoetis.cn',
  },
  {
    id: 'cn-pp-002',
    name: '福来恩（FRONTLINE）复方非泼罗尼体外驱虫滴剂（犬L号）',
    brand: '福来恩 FRONTLINE（勃林格殷格翰）',
    category: 'pest-prevention',
    description: '勃林格殷格翰旗下全球知名宠物体外驱虫品牌，含非泼罗尼与甲氧普烯，可快速杀灭跳蚤（成虫、卵、幼虫）及蜱虫，防水配置，每月使用一次，效果持续30天。',
    conditions: ['跳蚤', '蜱虫', '跳蚤卵和幼虫', '体外寄生虫'],
    pet_types: ['dog', 'cat'],
    price: 95,
    image_url: '',
    product_url: 'https://biahcn.com',
  },
  {
    id: 'cn-pp-003',
    name: '拜宠清Drontal宠物体内驱虫片（大型犬用）4片装',
    brand: '拜宠清 Drontal（礼蓝动保 Elanco）',
    category: 'pest-prevention',
    description: '礼蓝动保旗下广谱体内驱虫药，含吡喹酮、双羟萘酸噻嘧啶及非班太尔，可全面驱除犬只肠道线虫和绦虫，口服片剂使用方便，可与食物同服，建议每季度定期驱虫。',
    conditions: ['肠道线虫', '绦虫', '蛔虫', '钩虫', '体内寄生虫'],
    pet_types: ['dog'],
    price: 88,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-pp-004',
    name: '海乐妙宠物猫咪体内驱虫片（2kg以下）4片',
    brand: '海乐妙 Milbemax（诺华动保 Elanco）',
    category: 'pest-prevention',
    description: '适合猫咪使用的广谱体内驱虫片，主要成分米尔贝肟和吡喹酮，可驱除猫咪体内线虫、绦虫、心丝虫幼虫，可安全用于妊娠猫和哺乳猫，建议每3个月定期驱虫一次。',
    conditions: ['猫咪肠道线虫', '绦虫', '心丝虫预防', '体内寄生虫'],
    pet_types: ['cat'],
    price: 85,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-pp-005',
    name: '超可信犬用体内外一体驱虫滴剂（M号）',
    brand: '超可信 Advocate（拜耳/拜宠爽）',
    category: 'pest-prevention',
    description: '拜耳出品的宠物体内外综合驱虫产品，含吡虫啉与莫西菌素，可同时防治体外跳蚤、螨虫及体内线虫、心丝虫，一次用药双重防护，防水配方，按月使用。',
    conditions: ['跳蚤', '疥螨', '蠕形螨', '线虫', '心丝虫预防', '综合驱虫'],
    pet_types: ['dog'],
    price: 115,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-pp-006',
    name: '凯锐思宠物驱虫滴剂（猫咪体外驱虫）',
    brand: '凯锐思 Kairuisi',
    category: 'pest-prevention',
    description: '国产价格亲民的猫咪体外驱虫滴剂，含吡虫啉成分，可有效杀灭猫咪体表跳蚤及幼虫，防止再次感染，适合城市养猫家庭的日常驱虫防护，性价比高，每盒含3支。',
    conditions: ['跳蚤', '跳蚤卵', '体外寄生虫', '跳蚤感染'],
    pet_types: ['cat'],
    price: 45,
    image_url: '',
    product_url: '',
  },

  // =============================================================================
  // 12. 营养补充 NUTRITION (6 products)
  // =============================================================================
  {
    id: 'cn-nt-001',
    name: '卫仕宠物营养膏犬猫通用 120g',
    brand: '卫仕 NOURSE',
    category: 'nutrition',
    description: '卫仕经典高热量营养膏，含多种维生素、微量元素、卵磷脂和低聚果糖，科学配比帮助病后恢复、食欲不振及挑食宠物补充营养，适口性好，大部分宠物可直接舔食。',
    conditions: ['食欲不振', '病后恢复', '体重不足', '营养补充', '挑食'],
    pet_types: ['dog', 'cat'],
    price: 45,
    image_url: '',
    product_url: 'https://www.nourse.com.cn',
  },
  {
    id: 'cn-nt-002',
    name: '谷登金装优加宠物营养膏 200g',
    brand: '谷登 GOLDEN',
    category: 'nutrition',
    description: '谷登高规格营养膏，多种维生素科学配比矿物质，特别添加氨基酸、卵磷脂、鱼肝油和浓缩乳清蛋白，适合幼猫幼犬生长期补充、老年宠物营养支持及病后恢复期调理。',
    conditions: ['生长发育', '营养不良', '病后调理', '老年宠物', '术后恢复'],
    pet_types: ['dog', 'cat'],
    price: 65,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-nt-003',
    name: '红狗宠物维生素复合营养片 100片',
    brand: '红狗 RedDog',
    category: 'nutrition',
    description: '宠物专用复合维生素营养片，含维生素A、C、D、E、B族及铁、锌、钙等矿物质，全面补充宠物每日营养需求，适合偏食宠物、老年宠物及免疫力弱的宠物日常补充。',
    conditions: ['维生素缺乏', '免疫力低下', '偏食宠物', '老年宠物营养', '日常保健'],
    pet_types: ['dog', 'cat'],
    price: 78,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-nt-004',
    name: 'MAG宠物乳铁蛋白营养膏 100g',
    brand: 'MAG美格',
    category: 'nutrition',
    description: 'MAG出品的高端营养膏，以稀有的乳铁蛋白为特色成分，同时含高热量牛磺酸、铁质和多种维生素，特别适合贫血、感染恢复期、幼龄体弱及大手术后的宠物快速营养补充。',
    conditions: ['贫血', '感染恢复', '幼龄体弱', '术后营养支持', '体重过低'],
    pet_types: ['dog', 'cat'],
    price: 128,
    image_url: '',
    product_url: '',
  },
  {
    id: 'cn-nt-005',
    name: '普安特宠物卵磷脂毛发营养粉 150g',
    brand: '普安特 PUAINTA',
    category: 'nutrition',
    description: '以大豆卵磷脂为主要成分的宠物毛发营养粉，同时含生物素（维生素H）、Omega脂肪酸及B族维生素，可改善宠物毛发干枯、掉毛严重及皮肤干燥问题，适合长毛猫狗使用。',
    conditions: ['毛发干枯', '脱毛', '毛发无光泽', '皮肤干燥', '美毛'],
    pet_types: ['dog', 'cat'],
    price: 68,
    image_url: '',
    product_url: 'https://ispuainta.com',
  },
  {
    id: 'cn-nt-006',
    name: '法国皇家猫咪康复期营养主食罐 195g×6罐',
    brand: '法国皇家 Royal Canin',
    category: 'nutrition',
    description: '法国皇家专为猫咪康复期和营养不足期设计的高营养湿粮，热量密度高，含高消化率蛋白质和丰富的电解质，适合大病初愈、厌食、体重骤降及术后急需补充热量的猫咪。',
    conditions: ['病后康复', '厌食', '体重不足', '术后营养', '老年猫营养支持'],
    pet_types: ['cat'],
    price: 185,
    image_url: '',
    product_url: 'https://www.royalcanin.cn',
  },
];

async function main() {
  console.log('Starting Chinese pet product catalog seed...\n');

  try {
    // Drop existing collection and recreate
    await dropCollection();
    await createCollection();

    // Insert products
    await insertProducts(SAMPLE_PRODUCTS);

    console.log('\nSeed completed successfully!');
    console.log(`   Total products: ${SAMPLE_PRODUCTS.length}`);
    console.log('\nProduct breakdown by category:');
    const categories = SAMPLE_PRODUCTS.reduce<Record<string, number>>((acc, p) => {
      acc[p.category] = (acc[p.category] || 0) + 1;
      return acc;
    }, {});
    Object.entries(categories).forEach(([cat, count]) => {
      console.log(`   ${cat}: ${count} products`);
    });
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
}

main();
