/**
 * Seed script for pet products
 * Run with: npx tsx scripts/seed-products.ts
 */

import { config } from 'dotenv';
config({ path: '.env.local' });

import { createCollection, dropCollection, insertProducts, type Product } from '../src/services/zilliz';

// Comprehensive pet products catalog (50+ products)
const SAMPLE_PRODUCTS: Product[] = [
  // =============================================================================
  // WOUND CARE & RECOVERY (8 products)
  // =============================================================================
  {
    id: 'kong-ez-collar-dog-m',
    name: 'KONG EZ Soft E-Collar for Dogs - Medium',
    description: 'Soft, flexible recovery collar that is more comfortable than traditional plastic cones. Allows pets to eat, drink, and sleep comfortably while preventing them from licking wounds or surgical sites.',
    category: 'wound-care',
    conditions: ['wound', 'surgery', 'scratching', 'hot-spots', 'post-op', 'licking'],
    pet_types: ['dog'],
    price: 18.99,
    image_url: 'https://image.chewy.com/is/image/catalog/117386_MAIN._AC_SL600_V1629920631_.jpg',
    product_url: 'https://www.chewy.com/kong-ez-soft-e-collar-dogs-cats/dp/117386',
    brand: 'KONG',
  },
  {
    id: 'kong-ez-collar-cat',
    name: 'KONG EZ Soft E-Collar for Cats',
    description: 'Lightweight, soft recovery collar designed specifically for cats. Prevents licking and scratching while allowing normal activities. Ideal for post-surgery recovery.',
    category: 'wound-care',
    conditions: ['wound', 'surgery', 'scratching', 'post-op', 'licking'],
    pet_types: ['cat'],
    price: 14.99,
    image_url: 'https://image.chewy.com/is/image/catalog/117387_MAIN._AC_SL600_V1629920632_.jpg',
    product_url: 'https://www.chewy.com/kong-ez-soft-e-collar-cats/dp/117387',
    brand: 'KONG',
  },
  {
    id: 'vetericyn-wound-spray',
    name: 'Vetericyn Plus Antimicrobial Wound & Skin Care Spray',
    description: 'Non-toxic, steroid-free wound care spray that cleans wounds, treats infections, and speeds healing. Safe for all animal species and all wound types.',
    category: 'wound-care',
    conditions: ['wound', 'cut', 'scrape', 'burn', 'infection', 'hot-spots', 'abrasion'],
    pet_types: ['dog', 'cat'],
    price: 24.95,
    image_url: 'https://image.chewy.com/is/image/catalog/54171_MAIN._AC_SL600_V1538151358_.jpg',
    product_url: 'https://www.chewy.com/vetericyn-plus-antimicrobial-wound/dp/54171',
    brand: 'Vetericyn',
  },
  {
    id: 'pet-md-antiseptic-spray',
    name: 'Pet MD Antiseptic & Antifungal Spray',
    description: 'Medicated spray for dogs and cats that treats bacterial and fungal skin infections. Relieves itching and promotes healing of hot spots and wounds.',
    category: 'wound-care',
    conditions: ['wound', 'hot-spots', 'fungal-infection', 'bacterial-infection', 'itching'],
    pet_types: ['dog', 'cat'],
    price: 16.99,
    image_url: 'https://image.chewy.com/is/image/catalog/134799_MAIN._AC_SL600_V1606856478_.jpg',
    product_url: 'https://www.chewy.com/pet-md-antiseptic-antifungal-medicated/dp/134799',
    brand: 'Pet MD',
  },
  {
    id: 'sulfodene-wound-care',
    name: 'Sulfodene 3-Way Ointment for Dogs',
    description: 'Pain-relieving wound care ointment that treats wounds, cuts, and skin irritations. Provides antiseptic protection and promotes healing.',
    category: 'wound-care',
    conditions: ['wound', 'cut', 'scrape', 'skin-irritation', 'hot-spots'],
    pet_types: ['dog'],
    price: 9.99,
    image_url: 'https://image.chewy.com/is/image/catalog/52140_MAIN._AC_SL600_V1606856470_.jpg',
    product_url: 'https://www.chewy.com/sulfodene-3-way-ointment-dogs/dp/52140',
    brand: 'Sulfodene',
  },
  {
    id: 'neosporin-wound-care',
    name: 'Curicyn Original Formula Wound Care Solution',
    description: 'Veterinary-grade wound treatment that cleans and treats wounds without stinging. Safe for sensitive areas including eyes and ears.',
    category: 'wound-care',
    conditions: ['wound', 'cut', 'abrasion', 'burn', 'post-surgery'],
    pet_types: ['dog', 'cat'],
    price: 19.99,
    image_url: 'https://image.chewy.com/is/image/catalog/141511_MAIN._AC_SL600_V1606856581_.jpg',
    product_url: 'https://www.chewy.com/curicyn-original-formula-wound-care/dp/141511',
    brand: 'Curicyn',
  },
  {
    id: 'medipaw-boot',
    name: 'Medipaw Protective Boot for Dogs',
    description: 'Protective boot that covers wounds and bandages on paws. Waterproof and durable, prevents contamination during outdoor walks.',
    category: 'wound-care',
    conditions: ['paw-injury', 'wound', 'bandage-protection', 'post-surgery'],
    pet_types: ['dog'],
    price: 24.99,
    image_url: 'https://image.chewy.com/is/image/catalog/178953_MAIN._AC_SL600_V1606856589_.jpg',
    product_url: 'https://www.chewy.com/medipaw-protective-boot-dogs/dp/178953',
    brand: 'Medipaw',
  },
  {
    id: 'recovery-suit-dog',
    name: 'Suitical Recovery Suit for Dogs',
    description: 'Full-body recovery suit alternative to e-collars. Protects wounds, surgical sites, and skin conditions while allowing full mobility.',
    category: 'wound-care',
    conditions: ['surgery', 'wound', 'hot-spots', 'skin-condition', 'spay-neuter'],
    pet_types: ['dog'],
    price: 39.99,
    image_url: 'https://image.chewy.com/is/image/catalog/142753_MAIN._AC_SL600_V1606856585_.jpg',
    product_url: 'https://www.chewy.com/suitical-recovery-suit-dogs/dp/142753',
    brand: 'Suitical',
  },

  // =============================================================================
  // DIGESTIVE HEALTH (8 products)
  // =============================================================================
  {
    id: 'purina-fortiflora-dog',
    name: 'Purina Pro Plan FortiFlora Probiotic Dog Supplement',
    description: 'Veterinarian-recommended probiotic that promotes digestive health and immune support. Contains guaranteed live microorganisms to manage diarrhea.',
    category: 'digestive-health',
    conditions: ['diarrhea', 'upset-stomach', 'digestive-issues', 'gas', 'loose-stool'],
    pet_types: ['dog'],
    price: 32.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48370_MAIN._AC_SL600_V1647283712_.jpg',
    product_url: 'https://www.chewy.com/purina-pro-plan-veterinary/dp/48370',
    brand: 'Purina',
  },
  {
    id: 'purina-fortiflora-cat',
    name: 'Purina Pro Plan FortiFlora Probiotic Cat Supplement',
    description: 'Probiotic supplement for cats supporting digestive and immune health. Helps manage diarrhea and promotes intestinal balance.',
    category: 'digestive-health',
    conditions: ['diarrhea', 'upset-stomach', 'digestive-issues', 'vomiting'],
    pet_types: ['cat'],
    price: 32.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48371_MAIN._AC_SL600_V1647283694_.jpg',
    product_url: 'https://www.chewy.com/purina-pro-plan-veterinary/dp/48371',
    brand: 'Purina',
  },
  {
    id: 'pumpkin-supplement-dog',
    name: 'Native Pet Organic Pumpkin Fiber for Dogs',
    description: 'All-natural pumpkin powder that supports digestive health. Helps firm up loose stools and relieves constipation. Easy to mix with food.',
    category: 'digestive-health',
    conditions: ['diarrhea', 'constipation', 'digestive-issues', 'loose-stool', 'fiber'],
    pet_types: ['dog'],
    price: 21.99,
    image_url: 'https://image.chewy.com/is/image/catalog/187952_MAIN._AC_SL600_V1637687132_.jpg',
    product_url: 'https://www.chewy.com/native-pet-organic-pumpkin-fiber/dp/187952',
    brand: 'Native Pet',
  },
  {
    id: 'pumpkin-supplement-cat',
    name: 'Weruva Pumpkin Patch Up! Digestive Supplement for Cats',
    description: 'Pumpkin puree supplement that aids digestion and helps with hairball control. All-natural fiber source for cats with sensitive stomachs.',
    category: 'digestive-health',
    conditions: ['hairball', 'constipation', 'digestive-issues', 'vomiting'],
    pet_types: ['cat'],
    price: 15.99,
    image_url: 'https://image.chewy.com/is/image/catalog/149823_MAIN._AC_SL600_V1606856482_.jpg',
    product_url: 'https://www.chewy.com/weruva-pumpkin-patch-up-dog-cat-food/dp/149823',
    brand: 'Weruva',
  },
  {
    id: 'anti-diarrhea-dog',
    name: 'Pro-Pectalin Anti-Diarrhea Gel for Dogs & Cats',
    description: 'Fast-acting anti-diarrhea gel containing kaolin and pectin. Soothes irritated intestinal tract and firms stools quickly.',
    category: 'digestive-health',
    conditions: ['diarrhea', 'upset-stomach', 'loose-stool', 'intestinal-upset'],
    pet_types: ['dog', 'cat'],
    price: 18.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48459_MAIN._AC_SL600_V1606856467_.jpg',
    product_url: 'https://www.chewy.com/pro-pectalin-anti-diarrhea-gel-dogs/dp/48459',
    brand: 'Pro-Pectalin',
  },
  {
    id: 'digestive-enzymes-dog',
    name: 'NaturVet Digestive Enzymes Plus Probiotics for Dogs',
    description: 'Complete digestive support with enzymes and probiotics. Helps break down food, reduce gas, and improve nutrient absorption.',
    category: 'digestive-health',
    conditions: ['gas', 'bloating', 'digestive-issues', 'poor-absorption', 'food-intolerance'],
    pet_types: ['dog'],
    price: 24.99,
    image_url: 'https://image.chewy.com/is/image/catalog/47012_MAIN._AC_SL600_V1647283651_.jpg',
    product_url: 'https://www.chewy.com/naturvet-digestive-enzymes-plus/dp/47012',
    brand: 'NaturVet',
  },
  {
    id: 'hairball-remedy-cat',
    name: 'Laxatone Hairball Remedy Gel for Cats',
    description: 'Palatable gel that helps eliminate and prevent hairballs. Lubricates ingested hair for easy passage through digestive system.',
    category: 'digestive-health',
    conditions: ['hairball', 'vomiting', 'constipation', 'gagging'],
    pet_types: ['cat'],
    price: 12.99,
    image_url: 'https://image.chewy.com/is/image/catalog/52098_MAIN._AC_SL600_V1606856543_.jpg',
    product_url: 'https://www.chewy.com/laxatone-hairball-remedy-gel-cats/dp/52098',
    brand: 'Laxatone',
  },
  {
    id: 'bland-diet-dog',
    name: 'Under the Weather Rice & Chicken Bland Diet for Dogs',
    description: 'Ready-to-serve bland diet for dogs with upset stomachs. Freeze-dried for convenience, just add water. Gentle on sensitive digestive systems.',
    category: 'digestive-health',
    conditions: ['upset-stomach', 'vomiting', 'diarrhea', 'recovery', 'not-eating'],
    pet_types: ['dog'],
    price: 11.99,
    image_url: 'https://image.chewy.com/is/image/catalog/144387_MAIN._AC_SL600_V1606856579_.jpg',
    product_url: 'https://www.chewy.com/under-weather-rice-chicken-bland-diet/dp/144387',
    brand: 'Under the Weather',
  },

  // =============================================================================
  // EAR CARE (5 products)
  // =============================================================================
  {
    id: 'zymox-ear-solution',
    name: 'Zymox Otic Enzymatic Ear Solution with Hydrocortisone',
    description: 'Powerful enzymatic ear solution for acute and chronic ear infections. Contains hydrocortisone to relieve itching and inflammation.',
    category: 'ear-care',
    conditions: ['ear-infection', 'itchy-ears', 'ear-discharge', 'head-shaking', 'yeast-infection'],
    pet_types: ['dog', 'cat'],
    price: 26.99,
    image_url: 'https://image.chewy.com/is/image/catalog/50049_MAIN._AC_SL600_V1606856563_.jpg',
    product_url: 'https://www.chewy.com/zymox-otic-enzymatic-solution/dp/50049',
    brand: 'Zymox',
  },
  {
    id: 'virbac-ear-cleaner',
    name: 'Virbac Epi-Otic Advanced Ear Cleaner',
    description: 'Gentle ear cleaner that removes debris and excessive wax. Non-irritating formula suitable for routine ear cleaning and maintenance.',
    category: 'ear-care',
    conditions: ['ear-wax', 'dirty-ears', 'ear-odor', 'ear-maintenance'],
    pet_types: ['dog', 'cat'],
    price: 18.99,
    image_url: 'https://image.chewy.com/is/image/catalog/49857_MAIN._AC_SL600_V1647283659_.jpg',
    product_url: 'https://www.chewy.com/virbac-epi-otic-advanced-ear-cleaner/dp/49857',
    brand: 'Virbac',
  },
  {
    id: 'ear-mite-treatment',
    name: 'PetArmor Ear Mite & Tick Treatment for Dogs & Cats',
    description: 'Effective treatment for ear mites and ticks in ears. Contains pyrethrins to kill mites and soothe ear irritation.',
    category: 'ear-care',
    conditions: ['ear-mites', 'itchy-ears', 'head-shaking', 'ear-scratching'],
    pet_types: ['dog', 'cat'],
    price: 8.99,
    image_url: 'https://image.chewy.com/is/image/catalog/143841_MAIN._AC_SL600_V1606856577_.jpg',
    product_url: 'https://www.chewy.com/petarmor-ear-mite-tick-treatment-dogs/dp/143841',
    brand: 'PetArmor',
  },
  {
    id: 'vet-ear-powder',
    name: 'Miracle Care Ear Powder for Dogs & Cats',
    description: 'Ear powder that keeps ears dry and helps prevent infections. Ideal for dogs with floppy ears prone to moisture buildup.',
    category: 'ear-care',
    conditions: ['ear-moisture', 'ear-infection-prevention', 'grooming'],
    pet_types: ['dog', 'cat'],
    price: 9.99,
    image_url: 'https://image.chewy.com/is/image/catalog/46420_MAIN._AC_SL600_V1538151322_.jpg',
    product_url: 'https://www.chewy.com/miracle-care-ear-powder-dogs-cats/dp/46420',
    brand: 'Miracle Care',
  },
  {
    id: 'ear-wipes-dog',
    name: 'Pet MD Dog Ear Cleaner Wipes',
    description: 'Convenient ear cleaning wipes with aloe and eucalyptus. Removes wax, debris, and odor. Gentle enough for daily use.',
    category: 'ear-care',
    conditions: ['ear-wax', 'dirty-ears', 'ear-odor', 'ear-maintenance'],
    pet_types: ['dog'],
    price: 12.99,
    image_url: 'https://image.chewy.com/is/image/catalog/134798_MAIN._AC_SL600_V1606856478_.jpg',
    product_url: 'https://www.chewy.com/pet-md-dog-ear-cleaner-wipes/dp/134798',
    brand: 'Pet MD',
  },

  // =============================================================================
  // EYE CARE (5 products)
  // =============================================================================
  {
    id: 'vetericyn-eye-wash',
    name: 'Vetericyn Plus Antimicrobial Eye Wash',
    description: 'Sterile eye wash that cleans and soothes irritated eyes. Safe for daily use to remove debris and help with eye infections.',
    category: 'eye-care',
    conditions: ['eye-discharge', 'eye-infection', 'irritated-eyes', 'tear-stains', 'debris'],
    pet_types: ['dog', 'cat'],
    price: 15.99,
    image_url: 'https://image.chewy.com/is/image/catalog/141618_MAIN._AC_SL600_V1606856583_.jpg',
    product_url: 'https://www.chewy.com/vetericyn-plus-antimicrobial-all/dp/141618',
    brand: 'Vetericyn',
  },
  {
    id: 'eye-drops-dog',
    name: 'Nutri-Vet Eye Rinse for Dogs',
    description: 'Gentle eye rinse that removes debris and reduces irritation from allergies, pollutants, and foreign particles.',
    category: 'eye-care',
    conditions: ['eye-irritation', 'debris', 'allergies', 'eye-discharge'],
    pet_types: ['dog'],
    price: 8.99,
    image_url: 'https://image.chewy.com/is/image/catalog/46479_MAIN._AC_SL600_V1538151325_.jpg',
    product_url: 'https://www.chewy.com/nutri-vet-eye-rinse-dogs/dp/46479',
    brand: 'Nutri-Vet',
  },
  {
    id: 'tear-stain-remover',
    name: 'Angels Eyes Natural Tear Stain Remover for Dogs',
    description: 'Natural supplement that works from the inside out to eliminate tear stains. Contains cranberry and Oregon grape root.',
    category: 'eye-care',
    conditions: ['tear-stains', 'eye-discharge', 'eye-staining'],
    pet_types: ['dog'],
    price: 29.99,
    image_url: 'https://image.chewy.com/is/image/catalog/52548_MAIN._AC_SL600_V1647283702_.jpg',
    product_url: 'https://www.chewy.com/angels-eyes-natural-tear-stain/dp/52548',
    brand: 'Angels Eyes',
  },
  {
    id: 'eye-wipes-cat',
    name: 'Miracle Care Eye Clear Sterile Eye Wash Pads',
    description: 'Pre-moistened sterile pads for gentle eye cleaning. Removes discharge and debris while soothing irritated eyes.',
    category: 'eye-care',
    conditions: ['eye-discharge', 'crusty-eyes', 'eye-cleaning', 'tear-stains'],
    pet_types: ['dog', 'cat'],
    price: 7.99,
    image_url: 'https://image.chewy.com/is/image/catalog/46418_MAIN._AC_SL600_V1538151321_.jpg',
    product_url: 'https://www.chewy.com/miracle-care-eye-clear-sterile-eye/dp/46418',
    brand: 'Miracle Care',
  },
  {
    id: 'terramycin-eye-ointment',
    name: 'Terramycin Antibiotic Ophthalmic Ointment',
    description: 'Broad-spectrum antibiotic eye ointment for treating eye infections in dogs and cats. Effective against bacteria causing conjunctivitis.',
    category: 'eye-care',
    conditions: ['eye-infection', 'conjunctivitis', 'pink-eye', 'bacterial-infection'],
    pet_types: ['dog', 'cat'],
    price: 22.99,
    image_url: 'https://image.chewy.com/is/image/catalog/102267_MAIN._AC_SL600_V1606856461_.jpg',
    product_url: 'https://www.chewy.com/terramycin-antibiotic-ophthalmic/dp/102267',
    brand: 'Terramycin',
  },

  // =============================================================================
  // SKIN & ALLERGY (7 products)
  // =============================================================================
  {
    id: 'benadryl-allergy',
    name: 'Benadryl Ultratabs Antihistamine Allergy Relief',
    description: 'Over-the-counter antihistamine for dogs (with vet guidance) to relieve itching and allergic reactions. Always consult vet for dosing.',
    category: 'allergy-relief',
    conditions: ['itching', 'allergies', 'hives', 'allergic-reaction', 'seasonal-allergies', 'insect-bite'],
    pet_types: ['dog'],
    price: 9.99,
    image_url: 'https://image.chewy.com/is/image/catalog/182256_MAIN._AC_SL600_V1571766107_.jpg',
    product_url: 'https://www.chewy.com/benadryl-ultratabs-antihistamine/dp/182256',
    brand: 'Benadryl',
  },
  {
    id: 'anti-itch-spray-dog',
    name: 'Vet Best Hot Spot Spray for Dogs',
    description: 'Alcohol-free spray that provides immediate relief from itching and hot spots. Contains tea tree oil and aloe vera.',
    category: 'skin-care',
    conditions: ['hot-spots', 'itching', 'skin-irritation', 'scratching', 'allergies'],
    pet_types: ['dog'],
    price: 11.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48677_MAIN._AC_SL600_V1606856465_.jpg',
    product_url: 'https://www.chewy.com/vets-best-hot-spot-spray-dogs/dp/48677',
    brand: 'Vet Best',
  },
  {
    id: 'medicated-shampoo-dog',
    name: 'Veterinary Formula Clinical Care Antiseptic & Antifungal Shampoo',
    description: 'Medicated shampoo for bacterial and fungal skin infections. Contains benzethonium chloride and ketoconazole.',
    category: 'skin-care',
    conditions: ['skin-infection', 'fungal-infection', 'ringworm', 'hot-spots', 'dermatitis'],
    pet_types: ['dog', 'cat'],
    price: 13.99,
    image_url: 'https://image.chewy.com/is/image/catalog/136155_MAIN._AC_SL600_V1606856479_.jpg',
    product_url: 'https://www.chewy.com/veterinary-formula-clinical-care/dp/136155',
    brand: 'Veterinary Formula',
  },
  {
    id: 'oatmeal-shampoo-dog',
    name: 'Earthbath Oatmeal & Aloe Dog & Cat Shampoo',
    description: 'Soap-free shampoo with colloidal oatmeal and aloe vera. Relieves itching from dry, flaky skin and promotes a healthy coat.',
    category: 'skin-care',
    conditions: ['dry-skin', 'itching', 'flaky-skin', 'sensitive-skin'],
    pet_types: ['dog', 'cat'],
    price: 14.99,
    image_url: 'https://image.chewy.com/is/image/catalog/49662_MAIN._AC_SL600_V1647283656_.jpg',
    product_url: 'https://www.chewy.com/earthbath-oatmeal-aloe-dog-cat/dp/49662',
    brand: 'Earthbath',
  },
  {
    id: 'omega-3-skin-dog',
    name: 'Zesty Paws Omega Bites Skin & Coat Support for Dogs',
    description: 'Omega-3 fatty acid chews that support healthy skin and shiny coat. Contains EPA and DHA from fish oil and AlaskOmega.',
    category: 'skin-care',
    conditions: ['dry-skin', 'dull-coat', 'shedding', 'allergies', 'skin-health'],
    pet_types: ['dog'],
    price: 25.97,
    image_url: 'https://image.chewy.com/is/image/catalog/142591_MAIN._AC_SL600_V1647283716_.jpg',
    product_url: 'https://www.chewy.com/zesty-paws-omega-bites-skin-coat/dp/142591',
    brand: 'Zesty Paws',
  },
  {
    id: 'omega-3-skin-cat',
    name: 'Nordic Naturals Omega-3 Pet for Cats & Small Dogs',
    description: 'Liquid omega-3 supplement for cats that promotes healthy skin, shiny coat, and overall wellness. Easy to add to food.',
    category: 'skin-care',
    conditions: ['dry-skin', 'dull-coat', 'skin-health', 'shedding'],
    pet_types: ['cat'],
    price: 19.99,
    image_url: 'https://image.chewy.com/is/image/catalog/106665_MAIN._AC_SL600_V1606856462_.jpg',
    product_url: 'https://www.chewy.com/nordic-naturals-omega-3-pet-cats/dp/106665',
    brand: 'Nordic Naturals',
  },
  {
    id: 'chlorhexidine-wipes',
    name: 'Curaseb Chlorhexidine Wipes for Dogs & Cats',
    description: 'Antiseptic wipes with chlorhexidine and ketoconazole. Treats skin infections, hot spots, and ringworm between baths.',
    category: 'skin-care',
    conditions: ['skin-infection', 'hot-spots', 'ringworm', 'yeast-infection', 'bacterial-infection'],
    pet_types: ['dog', 'cat'],
    price: 15.99,
    image_url: 'https://image.chewy.com/is/image/catalog/153951_MAIN._AC_SL600_V1606856488_.jpg',
    product_url: 'https://www.chewy.com/curaseb-chlorhexidine-wipes-dogs-cats/dp/153951',
    brand: 'Curaseb',
  },

  // =============================================================================
  // ANXIETY & CALMING (6 products)
  // =============================================================================
  {
    id: 'thundershirt-dog',
    name: 'ThunderShirt Classic Anxiety & Calming Vest for Dogs',
    description: 'Patented design applies gentle, constant pressure to calm anxiety. Drug-free solution for thunder, fireworks, and separation anxiety.',
    category: 'anxiety-relief',
    conditions: ['anxiety', 'fear', 'thunder', 'fireworks', 'separation-anxiety', 'travel'],
    pet_types: ['dog'],
    price: 44.95,
    image_url: 'https://image.chewy.com/is/image/catalog/47718_MAIN._AC_SL600_V1606856486_.jpg',
    product_url: 'https://www.chewy.com/thundershirt-classic-anxiety-calming/dp/47718',
    brand: 'ThunderShirt',
  },
  {
    id: 'thundershirt-cat',
    name: 'ThunderShirt Classic Anxiety & Calming Vest for Cats',
    description: 'Gentle pressure wrap designed for cats to reduce anxiety from travel, vet visits, and loud noises. Drug-free calming solution.',
    category: 'anxiety-relief',
    conditions: ['anxiety', 'fear', 'travel', 'vet-visit', 'loud-noises'],
    pet_types: ['cat'],
    price: 39.95,
    image_url: 'https://image.chewy.com/is/image/catalog/47722_MAIN._AC_SL600_V1606856486_.jpg',
    product_url: 'https://www.chewy.com/thundershirt-classic-anxiety-calming/dp/47722',
    brand: 'ThunderShirt',
  },
  {
    id: 'feliway-diffuser',
    name: 'Feliway Classic Calming Diffuser Kit for Cats',
    description: 'Pheromone diffuser that reduces stress-related behaviors in cats including scratching, spraying, and hiding. Covers 700 sq ft.',
    category: 'anxiety-relief',
    conditions: ['anxiety', 'stress', 'spraying', 'scratching', 'hiding', 'new-home'],
    pet_types: ['cat'],
    price: 34.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48866_MAIN._AC_SL600_V1647283634_.jpg',
    product_url: 'https://www.chewy.com/feliway-classic-30-day-starter-kit/dp/48866',
    brand: 'Feliway',
  },
  {
    id: 'adaptil-diffuser',
    name: 'Adaptil Calming Diffuser Kit for Dogs',
    description: 'Dog appeasing pheromone diffuser that helps reduce stress and anxiety. Ideal for staying home alone, loud noises, and new environments.',
    category: 'anxiety-relief',
    conditions: ['anxiety', 'stress', 'separation-anxiety', 'fear', 'new-home'],
    pet_types: ['dog'],
    price: 34.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48869_MAIN._AC_SL600_V1647283635_.jpg',
    product_url: 'https://www.chewy.com/adaptil-30-day-starter-kit-calming/dp/48869',
    brand: 'Adaptil',
  },
  {
    id: 'calming-chews-dog',
    name: 'Zesty Paws Calming Bites for Dogs',
    description: 'Calming chews with Suntheanine, organic chamomile, and valerian root. Helps dogs relax during stressful situations.',
    category: 'anxiety-relief',
    conditions: ['anxiety', 'stress', 'hyperactivity', 'nervousness', 'travel'],
    pet_types: ['dog'],
    price: 25.97,
    image_url: 'https://image.chewy.com/is/image/catalog/142612_MAIN._AC_SL600_V1647283717_.jpg',
    product_url: 'https://www.chewy.com/zesty-paws-calming-bites-dogs/dp/142612',
    brand: 'Zesty Paws',
  },
  {
    id: 'calming-treats-cat',
    name: 'VetriScience Composure Calming Chews for Cats',
    description: 'Bite-sized calming chews with Colostrum, L-Theanine, and Thiamine. Supports relaxation without sedation.',
    category: 'anxiety-relief',
    conditions: ['anxiety', 'stress', 'travel', 'vet-visit', 'nervousness'],
    pet_types: ['cat'],
    price: 21.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48456_MAIN._AC_SL600_V1647283632_.jpg',
    product_url: 'https://www.chewy.com/vetriscience-composure-calming/dp/48456',
    brand: 'VetriScience',
  },

  // =============================================================================
  // FIRST AID (5 products)
  // =============================================================================
  {
    id: 'nutri-vet-first-aid-kit',
    name: 'Nutri-Vet Pet First Aid Kit',
    description: 'Comprehensive first aid kit with bandages, antiseptic, scissors, tweezers, and emergency guide. Essential for home and travel.',
    category: 'first-aid',
    conditions: ['emergency', 'injury', 'wound', 'travel', 'preparedness'],
    pet_types: ['dog', 'cat'],
    price: 19.99,
    image_url: 'https://image.chewy.com/is/image/catalog/134413_MAIN._AC_SL600_V1606856573_.jpg',
    product_url: 'https://www.chewy.com/nutri-vet-pet-first-aid-kit/dp/134413',
    brand: 'Nutri-Vet',
  },
  {
    id: 'styptic-powder',
    name: 'Miracle Care Kwik Stop Styptic Powder',
    description: 'Fast-acting styptic powder that stops bleeding from minor cuts and nail trims within seconds. Essential for nail trimming.',
    category: 'first-aid',
    conditions: ['bleeding', 'nail-trim', 'minor-cut', 'wound'],
    pet_types: ['dog', 'cat'],
    price: 8.99,
    image_url: 'https://image.chewy.com/is/image/catalog/46422_MAIN._AC_SL600_V1538151323_.jpg',
    product_url: 'https://www.chewy.com/miracle-care-kwik-stop-styptic/dp/46422',
    brand: 'Miracle Care',
  },
  {
    id: 'pet-bandage',
    name: '3M Vetrap Bandaging Tape',
    description: 'Self-adhering bandage tape that sticks to itself, not fur. Lightweight, breathable, and easy to apply for wound dressing.',
    category: 'first-aid',
    conditions: ['wound', 'bandaging', 'injury', 'paw-injury'],
    pet_types: ['dog', 'cat'],
    price: 7.99,
    image_url: 'https://image.chewy.com/is/image/catalog/102116_MAIN._AC_SL600_V1606856460_.jpg',
    product_url: 'https://www.chewy.com/3m-vetrap-bandaging-tape-2-inches/dp/102116',
    brand: '3M',
  },
  {
    id: 'hydrogen-peroxide',
    name: 'Hydrogen Peroxide 3% USP for Pet First Aid',
    description: 'Medical-grade hydrogen peroxide for cleaning wounds and inducing vomiting in emergencies (only under vet guidance).',
    category: 'first-aid',
    conditions: ['wound-cleaning', 'emergency', 'poisoning'],
    pet_types: ['dog', 'cat'],
    price: 3.99,
    image_url: 'https://image.chewy.com/is/image/catalog/182260_MAIN._AC_SL600_V1571766108_.jpg',
    product_url: 'https://www.chewy.com/swan-hydrogen-peroxide-3-first-aid/dp/182260',
    brand: 'Swan',
  },
  {
    id: 'pet-thermometer',
    name: 'iProven Pet Thermometer for Dogs & Cats',
    description: 'Fast, accurate digital thermometer for pets. Flexible tip for comfort, fever alert, and memory recall function.',
    category: 'first-aid',
    conditions: ['fever', 'illness', 'temperature-check', 'monitoring'],
    pet_types: ['dog', 'cat'],
    price: 14.99,
    image_url: 'https://image.chewy.com/is/image/catalog/189732_MAIN._AC_SL600_V1606856591_.jpg',
    product_url: 'https://www.chewy.com/iproven-pet-thermometer-dogs-cats/dp/189732',
    brand: 'iProven',
  },

  // =============================================================================
  // DENTAL CARE (4 products)
  // =============================================================================
  {
    id: 'virbac-toothpaste',
    name: 'Virbac C.E.T. Enzymatic Dog & Cat Toothpaste',
    description: 'Enzymatic toothpaste that fights plaque and freshens breath. Poultry flavor, no rinsing required. Safe to swallow.',
    category: 'dental-care',
    conditions: ['bad-breath', 'plaque', 'dental-disease', 'gum-disease'],
    pet_types: ['dog', 'cat'],
    price: 12.95,
    image_url: 'https://image.chewy.com/is/image/catalog/49855_MAIN._AC_SL600_V1647283658_.jpg',
    product_url: 'https://www.chewy.com/virbac-cet-enzymatic-toothpaste/dp/49855',
    brand: 'Virbac',
  },
  {
    id: 'dental-water-additive',
    name: 'Nylabone Advanced Oral Care Water Additive for Dogs',
    description: 'Tasteless, odorless water additive that fights plaque and tartar. Simply add to water bowl for daily dental care.',
    category: 'dental-care',
    conditions: ['bad-breath', 'plaque', 'tartar', 'dental-maintenance'],
    pet_types: ['dog'],
    price: 9.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48215_MAIN._AC_SL600_V1606856464_.jpg',
    product_url: 'https://www.chewy.com/nylabone-advanced-oral-care-liquid/dp/48215',
    brand: 'Nylabone',
  },
  {
    id: 'dental-chews-dog',
    name: 'Greenies Original Dental Dog Treats',
    description: 'Vet-recommended dental treats that clean teeth, freshen breath, and fight tartar. Unique texture reaches deep between teeth.',
    category: 'dental-care',
    conditions: ['bad-breath', 'plaque', 'tartar', 'dental-maintenance'],
    pet_types: ['dog'],
    price: 27.98,
    image_url: 'https://image.chewy.com/is/image/catalog/44880_MAIN._AC_SL600_V1647283627_.jpg',
    product_url: 'https://www.chewy.com/greenies-original-dental-dog-treats/dp/44880',
    brand: 'Greenies',
  },
  {
    id: 'dental-treats-cat',
    name: 'Greenies Feline Dental Cat Treats',
    description: 'Crunchy dental treats for cats that reduce tartar and plaque buildup. Delicious flavor cats love with added vitamins.',
    category: 'dental-care',
    conditions: ['bad-breath', 'plaque', 'tartar', 'dental-maintenance'],
    pet_types: ['cat'],
    price: 5.99,
    image_url: 'https://image.chewy.com/is/image/catalog/113561_MAIN._AC_SL600_V1647283706_.jpg',
    product_url: 'https://www.chewy.com/greenies-feline-oven-roasted-chicken/dp/113561',
    brand: 'Greenies',
  },

  // =============================================================================
  // JOINT & MOBILITY (4 products)
  // =============================================================================
  {
    id: 'cosequin-joint-dog',
    name: 'Nutramax Cosequin Maximum Strength Joint Supplement for Dogs',
    description: '#1 vet-recommended joint supplement with glucosamine and chondroitin. Supports cartilage and joint health in dogs.',
    category: 'joint-health',
    conditions: ['arthritis', 'joint-pain', 'limping', 'mobility-issues', 'hip-dysplasia', 'stiffness'],
    pet_types: ['dog'],
    price: 42.99,
    image_url: 'https://image.chewy.com/is/image/catalog/46665_MAIN._AC_SL600_V1680193831_.jpg',
    product_url: 'https://www.chewy.com/nutramax-cosequin-maximum-strength/dp/46665',
    brand: 'Nutramax',
  },
  {
    id: 'cosequin-joint-cat',
    name: 'Nutramax Cosequin Joint Health Supplement for Cats',
    description: 'Joint health supplement formulated specifically for cats. Supports cartilage health and comfortable mobility.',
    category: 'joint-health',
    conditions: ['arthritis', 'joint-pain', 'mobility-issues', 'stiffness', 'senior-cat'],
    pet_types: ['cat'],
    price: 22.99,
    image_url: 'https://image.chewy.com/is/image/catalog/46667_MAIN._AC_SL600_V1647283647_.jpg',
    product_url: 'https://www.chewy.com/nutramax-cosequin-joint-health/dp/46667',
    brand: 'Nutramax',
  },
  {
    id: 'hip-joint-chews-dog',
    name: 'Zesty Paws Mobility Bites Hip & Joint Support for Dogs',
    description: 'Glucosamine chews with MSM, chondroitin, and OptiMSM. Supports hip and joint function for active and senior dogs.',
    category: 'joint-health',
    conditions: ['arthritis', 'joint-pain', 'hip-dysplasia', 'mobility-issues', 'senior-dog'],
    pet_types: ['dog'],
    price: 25.97,
    image_url: 'https://image.chewy.com/is/image/catalog/142587_MAIN._AC_SL600_V1647283715_.jpg',
    product_url: 'https://www.chewy.com/zesty-paws-mobility-bites-hip-joint/dp/142587',
    brand: 'Zesty Paws',
  },
  {
    id: 'dasuquin-advanced',
    name: 'Nutramax Dasuquin with MSM Joint Health Supplement',
    description: 'Advanced joint supplement with ASU, glucosamine, chondroitin, and MSM. Comprehensive support for dogs with joint issues.',
    category: 'joint-health',
    conditions: ['arthritis', 'joint-pain', 'severe-joint-issues', 'mobility-issues'],
    pet_types: ['dog'],
    price: 89.99,
    image_url: 'https://image.chewy.com/is/image/catalog/46669_MAIN._AC_SL600_V1680193832_.jpg',
    product_url: 'https://www.chewy.com/nutramax-dasuquin-msm-soft-chews/dp/46669',
    brand: 'Nutramax',
  },

  // =============================================================================
  // FLEA & TICK (4 products)
  // =============================================================================
  {
    id: 'frontline-plus-dog',
    name: 'Frontline Plus Flea & Tick Treatment for Dogs',
    description: 'Trusted flea and tick treatment that kills fleas, eggs, larvae, and ticks. Waterproof, 30-day protection.',
    category: 'flea-tick',
    conditions: ['fleas', 'ticks', 'flea-eggs', 'prevention'],
    pet_types: ['dog'],
    price: 74.99,
    image_url: 'https://image.chewy.com/is/image/catalog/47848_MAIN._AC_SL600_V1647283536_.jpg',
    product_url: 'https://www.chewy.com/frontline-plus-flea-tick-spot/dp/47848',
    brand: 'Frontline',
  },
  {
    id: 'frontline-plus-cat',
    name: 'Frontline Plus Flea & Tick Treatment for Cats',
    description: 'Monthly topical treatment that kills fleas and ticks on cats. Waterproof and long-lasting protection.',
    category: 'flea-tick',
    conditions: ['fleas', 'ticks', 'flea-eggs', 'prevention'],
    pet_types: ['cat'],
    price: 54.99,
    image_url: 'https://image.chewy.com/is/image/catalog/47849_MAIN._AC_SL600_V1647283536_.jpg',
    product_url: 'https://www.chewy.com/frontline-plus-flea-tick-spot/dp/47849',
    brand: 'Frontline',
  },
  {
    id: 'seresto-collar-dog',
    name: 'Seresto Flea & Tick Collar for Dogs',
    description: '8-month flea and tick protection in a single collar. Kills and repels fleas and ticks on contact. Water-resistant.',
    category: 'flea-tick',
    conditions: ['fleas', 'ticks', 'prevention', 'long-term-protection'],
    pet_types: ['dog'],
    price: 63.98,
    image_url: 'https://image.chewy.com/is/image/catalog/115589_MAIN._AC_SL600_V1647283708_.jpg',
    product_url: 'https://www.chewy.com/seresto-flea-tick-collar-dogs/dp/115589',
    brand: 'Seresto',
  },
  {
    id: 'capstar-flea',
    name: 'Capstar Flea Oral Treatment for Dogs & Cats',
    description: 'Fast-acting oral tablet that starts killing fleas within 30 minutes. Safe for daily use when needed.',
    category: 'flea-tick',
    conditions: ['fleas', 'flea-infestation', 'immediate-relief'],
    pet_types: ['dog', 'cat'],
    price: 34.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48348_MAIN._AC_SL600_V1647283630_.jpg',
    product_url: 'https://www.chewy.com/capstar-flea-oral-treatment-dogs-2-25/dp/48348',
    brand: 'Capstar',
  },

  // =============================================================================
  // NUTRITION & SUPPLEMENTS (4 products)
  // =============================================================================
  {
    id: 'nutri-cal-supplement',
    name: 'Tomlyn Nutri-Cal High Calorie Nutritional Gel',
    description: 'High-calorie supplement for pets not eating well or recovering from illness. Palatable gel with vitamins and nutrients.',
    category: 'nutrition',
    conditions: ['not-eating', 'weight-loss', 'recovery', 'low-energy', 'illness', 'appetite-loss'],
    pet_types: ['dog', 'cat'],
    price: 14.99,
    image_url: 'https://image.chewy.com/is/image/catalog/52234_MAIN._AC_SL600_V1606856547_.jpg',
    product_url: 'https://www.chewy.com/tomlyn-nutri-cal-high-calorie/dp/52234',
    brand: 'Tomlyn',
  },
  {
    id: 'multivitamin-dog',
    name: 'Zesty Paws Multivitamin Bites for Dogs',
    description: 'Complete multivitamin with over 35 vitamins, minerals, and nutrients. Supports immune, heart, skin, and digestive health.',
    category: 'nutrition',
    conditions: ['vitamin-deficiency', 'general-health', 'immune-support', 'senior-dog'],
    pet_types: ['dog'],
    price: 25.97,
    image_url: 'https://image.chewy.com/is/image/catalog/142593_MAIN._AC_SL600_V1647283716_.jpg',
    product_url: 'https://www.chewy.com/zesty-paws-multivitamin-bites-dogs/dp/142593',
    brand: 'Zesty Paws',
  },
  {
    id: 'multivitamin-cat',
    name: 'VetriScience NuCat Senior Multivitamin for Cats',
    description: 'Comprehensive daily supplement for senior cats with vitamins, minerals, and omega fatty acids for overall wellness.',
    category: 'nutrition',
    conditions: ['senior-cat', 'vitamin-deficiency', 'general-health', 'aging'],
    pet_types: ['cat'],
    price: 15.99,
    image_url: 'https://image.chewy.com/is/image/catalog/48461_MAIN._AC_SL600_V1647283633_.jpg',
    product_url: 'https://www.chewy.com/vetriscience-nucat-senior/dp/48461',
    brand: 'VetriScience',
  },
  {
    id: 'appetite-stimulant-cat',
    name: 'Tomlyn Nutri-Stat High Calorie Supplement for Cats',
    description: 'High-calorie gel specifically formulated for cats. Supports cats with poor appetite, stress, or recovering from illness.',
    category: 'nutrition',
    conditions: ['not-eating', 'appetite-loss', 'weight-loss', 'recovery', 'stress'],
    pet_types: ['cat'],
    price: 11.99,
    image_url: 'https://image.chewy.com/is/image/catalog/52237_MAIN._AC_SL600_V1606856548_.jpg',
    product_url: 'https://www.chewy.com/tomlyn-nutri-stat-high-calorie/dp/52237',
    brand: 'Tomlyn',
  },
];

async function main() {
  console.log('🐾 Starting product seed...\n');

  try {
    // Drop existing collection and recreate
    await dropCollection();
    await createCollection();

    // Insert products
    await insertProducts(SAMPLE_PRODUCTS);

    console.log('\n✅ Seed completed successfully!');
    console.log(`   Total products: ${SAMPLE_PRODUCTS.length}`);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
}

main();
